### ISSUE TITLE
Telegram Spam(Please Read!)

### ISSUE THREAD

**Issue by virgocerco** [un1cum/CleanerPRO#1]
Your Spammer Repo is great but it's outdated please update the sms because it's not working properly and telegram spam is doesn't work anymore because of loop error in code and said in terminal i have error and check variable in my input please fix:) im amateur only thankyou sm!

By the way i messaged here because there is no issue option in spammer repo

**Comment by un1cum** [comment]
Thank you for pointing out the error, I will check and fix it.
